name: Deploy Angular Projects

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    
    - name: Build and Deploy
      run: |
        mkdir -p deploy
        
        # Build Day1 Phase1
        cd Day1/Phase1
        npm install --legacy-peer-deps
        ng build --base-href="/Angular/day1-phase1/"
        cp -r dist/*/* ../../deploy/
        mkdir -p ../../deploy/day1-phase1
        cp -r dist/*/* ../../deploy/day1-phase1/
        cd ../..
        
        # Build Day1 Project2
        cd Day1/Project2
        npm install --legacy-peer-deps
        ng build --base-href="/Angular/day1-project2/"
        mkdir -p ../../deploy/day1-project2
        cp -r dist/*/* ../../deploy/day1-project2/
        cd ../..
        
        # Build Day2 Phase1
        cd Day2/Phase1
        npm install --legacy-peer-deps
        ng build --base-href="/Angular/day2-phase1/"
        mkdir -p ../../deploy/day2-phase1
        cp -r dist/*/* ../../deploy/day2-phase1/
        cd ../..
        
        # Build Day2 Project2
        cd Day2/Project2
        npm install --legacy-peer-deps
        ng build --base-href="/Angular/day2-project2/"
        mkdir -p ../../deploy/day2-project2
        cp -r dist/*/* ../../deploy/day2-project2/
        cd ../..
        
        # Create main index
        cat > deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Angular Training Projects</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
                .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 10px; }
                h1 { text-align: center; color: #333; }
                .project { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
                .project a { color: #007bff; text-decoration: none; font-weight: bold; }
                .project a:hover { text-decoration: underline; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 Angular Training Projects</h1>
                <div class="project">
                    <h3>Day 1 - Phase 1</h3>
                    <a href="./day1-phase1/">View Project →</a>
                </div>
                <div class="project">
                    <h3>Day 1 - Project 2</h3>
                    <a href="./day1-project2/">View Project →</a>
                </div>
                <div class="project">
                    <h3>Day 2 - Phase 1</h3>
                    <a href="./day2-phase1/">View Project →</a>
                </div>
                <div class="project">
                    <h3>Day 2 - Project 2</h3>
                    <a href="./day2-project2/">View Project →</a>
                </div>
            </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy